CREATE DATABASE PRUEBA
    LOCALE 'sv_SE.utf8'
    TEMPLATE template0;

CREATE SCHEMA [IF NOT EXISTS] public;

CREATE TABLE public."alumno"
(
    id_alumnoGENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(25),
    apellido character varying(25),
    rut character varying(25),
    curso character varying(25),
    PRIMARY KEY (id_alumno)
)